spring:
  datasource:
    username: root
    password: yourpassword
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/fzh?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"
    

mybatis:
  type-aliases-package: com.example.mybatistest.entity
  mapper-locations: classpath:com/example/mybatistest/mapper/*.xml

server:
  port: 8082
  
mvc:
  static-path-pattern: /static/**